//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlDieselWS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoEnergex
    {
        public int EmpleadoEnergexId { get; set; }
        public Nullable<int> NumEmpleadoMexLog { get; set; }
        public string NumEmpleadoEnergex { get; set; }
        public int CentroCostosId { get; set; }
    }
}
