//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlDieselWS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LitrosCargados
    {
        public int LitrosCargadosId { get; set; }
        public Nullable<int> SolicitudDepositoId { get; set; }
        public Nullable<int> SolicitudDepositoTraficoId { get; set; }
        public Nullable<int> MovimientoExternoId { get; set; }
        public string FolioEnergex { get; set; }
        public Nullable<decimal> LitrosSolicitados { get; set; }
        public Nullable<decimal> LitrosCargados1 { get; set; }
        public int Estatus { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> SolicitudDepositoComplementoId { get; set; }
        public string NumeroEmpleadoEnergex { get; set; }
        public Nullable<int> OrdenIdentificadorTicket { get; set; }
        public Nullable<int> IdentificadorTicket { get; set; }
        public string NumeroTarjetaTicket { get; set; }
    }
}
