//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlDieselWS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CombustibleEntities : DbContext
    {
        public CombustibleEntities()
            : base("name=CombustibleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutorizacionesParcialesEnergex> AutorizacionesParcialesEnergex { get; set; }
        public virtual DbSet<LitrosCargados> LitrosCargados { get; set; }
        public virtual DbSet<SolicitudDeposito> SolicitudDeposito { get; set; }
        public virtual DbSet<EmpleadoEnergex> EmpleadoEnergex { get; set; }
        public virtual DbSet<SolicitudDepositoTraficoDiesel> SolicitudDepositoTraficoDiesel { get; set; }
        public virtual DbSet<AutorizacionesEnergex> AutorizacionesEnergex { get; set; }
        public virtual DbSet<SolicitudDepositoComplemento> SolicitudDepositoComplemento { get; set; }
        public virtual DbSet<SolicitudDepositoTrafico> SolicitudDepositoTrafico { get; set; }
    
        public virtual int CancelarSolicitudDispensario(Nullable<int> solicitudDepositoId)
        {
            var solicitudDepositoIdParameter = solicitudDepositoId.HasValue ?
                new ObjectParameter("SolicitudDepositoId", solicitudDepositoId) :
                new ObjectParameter("SolicitudDepositoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CancelarSolicitudDispensario", solicitudDepositoIdParameter);
        }
    
        public virtual ObjectResult<ObtenerListaSolicitudDispensarioActivas_Result> ObtenerListaSolicitudDispensarioActivas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerListaSolicitudDispensarioActivas_Result>("ObtenerListaSolicitudDispensarioActivas");
        }
    }
}
