//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlDieselWS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDepositoTraficoDiesel
    {
        public int SolicitudDepositoDieselId { get; set; }
        public int SolicitudDepositoId { get; set; }
        public decimal DieselLitros { get; set; }
        public int SolicitudDepositoStatusId { get; set; }
        public int SolicitudDepositoTipo { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<int> IdSolicitudTrafico { get; set; }
        public Nullable<int> TipoTarjetaId { get; set; }
        public string Justificacion { get; set; }
    }
}
