//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlDieselWS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDepositoComplemento
    {
        public int SolicitudDepositoComplementoId { get; set; }
        public int SolicitudDepositoId { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<int> TipoTarjetaId { get; set; }
        public bool EnviadoDispensario { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<int> TipoComplementoId { get; set; }
    }
}
