//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlDieselWS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDepositoTrafico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudDepositoTrafico()
        {
            this.SolicitudDepositoTraficoDiesel = new HashSet<SolicitudDepositoTraficoDiesel>();
        }
    
        public int SolicitudDepositoId { get; set; }
        public int ClaveOrden { get; set; }
        public string FolioOrden { get; set; }
        public string NombreOperador { get; set; }
        public int KilometrosRuta { get; set; }
        public string CiudadOrigen { get; set; }
        public string CiudadDestino { get; set; }
        public Nullable<decimal> RendimientoConfigurado { get; set; }
        public Nullable<int> Transportador { get; set; }
        public Nullable<int> Traslado { get; set; }
        public Nullable<int> Sistema { get; set; }
        public Nullable<int> NumeroEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudDepositoTraficoDiesel> SolicitudDepositoTraficoDiesel { get; set; }
    }
}
