//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mlDieselWS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDeposito
    {
        public int SolicitudDepositoId { get; set; }
        public int SolicitudDepositoSistemaId { get; set; }
        public int ClaveCarga { get; set; }
        public int KilometrosRuta { get; set; }
        public string NombreCliente { get; set; }
        public string NombreTerminal { get; set; }
        public Nullable<int> NumeroEmpleado { get; set; }
        public string NombreOperador { get; set; }
        public string CiudadOrigen { get; set; }
        public string CiudadDestino { get; set; }
        public string CiudadRegreso { get; set; }
        public string NumeroEconomico { get; set; }
        public decimal DieselLitros { get; set; }
        public decimal DieselReservaLitros { get; set; }
        public int SolicitudDepositoStatusId { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public bool IsTarjeta { get; set; }
        public Nullable<int> TipoTarjetaId { get; set; }
        public bool IsManual { get; set; }
        public string FolioEnergex { get; set; }
    }
}
